name: Pylint QA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3

      - name: List contents of Backend directory
        run: ls Backend

      - name: Change directory to Backend and activate virtual environment
        run: |
          cd Backend
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Analysing the code with pylint
        run: |
          pylint --rcfile=.pylintrc $(git ls-files '*.py')
